### PR TITLE
Large files used by new All-in-one Tool 

### PR DESCRIPTION
**Pull request by TomasKello**

### CODE REVIEW

**Comment by tvami** [comment]
+alca

**Comment by TomasKello** [comment]
@tvami please merge this once tests are done, it is needed for tests in another [PR](https://github.com/cms-sw/cmssw/pull/38304)

**Comment by tvami** [comment]
+alca

**Comment by rappoccio** [comment]
+1

Needed for new "all-in-one" tool from TRK DPG described [here](https://github.com/cms-sw/cmssw/pull/38304).

**Comment by mmusich** [comment]
Despite the +1, this is not merged.
As https://github.com/cms-sw/cmssw/pull/38304 requires it, if it is not merged in the same IB, unit tests will start to fail.

**Comment by smuzaffar** [comment]
+externals

**Comment by mmusich** [comment]
I see that in PR https://github.com/cms-sw/cmssw/pull/40019  [unit tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e7e90e/28901/unitTests/src/Alignment/OfflineValidation/test/DMRall/testing.log) are failing because of missing input files:

```
Exception Message:
Path /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-08-2000/poison/Alignment/OfflineValidation/data/lumiPerRun_Run2.txt is a directory, not a file

Failure running DMR trends: status 1
status = 256
```

why is it still trying to look in `poison` ?

**Pull request merged**
