### PR TITLE
PolyLine data files for TkAlMap (tracker maps for alignment)

### PR DESCRIPTION
**Pull request by SenneVanPutte**
Moving txt files to here as requested in 
https://github.com/cms-sw/cmssw/pull/31376

### CODE REVIEW

**Comment by mrodozov** [comment]
remove them from cms-sw/cmssw#31376

**Comment by SenneVanPutte** [comment]
I was waiting for them to be added here, so I can test out the TkAlMap implementation in this setup.
But if you prefer I can remove them, and alter the setup in two different commits.

**Comment by mrodozov** [comment]
You don't have to alter anything if the alteration you mean is about how do you refer to the files. they should be refered to as they were i.e.  
`Alignment/OfflineValidation/data/TkAlMap/Relative_TPolyLine_Pixel_BPIX_L1.txt`
you just have to mention this pull request like this in 31376:
`please test with https://github.com/cms-data/Alignment-OfflineValidation/pull/1`

**Comment by tlampen** [comment]
+alca

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
