### PR TITLE
new TkAlMap version (xy inversion fix)

### PR DESCRIPTION
**Pull request by SenneVanPutte**
xy coordinates where flipped to be equivalent everywhere

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test
lets refresh the test results for 12.3.X
FYI @qliphy , @perrotta  , this looks ready to go in

**Comment by perrotta** [comment]
@SenneVanPutte , in order not to sign it blindly, could you please add to the PR description two lines of explanation, or a link to a presentation (at an AlCa meeting?), or anything else that can explain what you are doing and why?
@tvami your signature was done in last November: is this cms-data change still needed now in February?

**Comment by tvami** [comment]
I think it's usueful to have it, but not a showstopper not to have it, i.e. I think we can merge it in 12_3_X

**Comment by perrotta** [comment]
> I think it's usueful to have it, but not a showstopper not to have it, i.e. I think we can merge it in 12_3_X

Thank you @tvami 
And, out of curiosity: what is it?

**Comment by mmusich** [comment]
It's needed to make TrackerMap plots formatted as in the alignment paper [TRK-20-001](https://cms.cern.ch/iCMS/analysisadmin/cadilines?line=TRK-20-001&tp=an&id=2384&ancode=TRK-20-001) e.g.
Screenshot_20220223-213235_Samsung Notes

**Comment by perrotta** [comment]
+1

**Pull request merged**
